name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: ['11.0.4', '12.0.2']

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Gradle
      run: ./gradlew build
